<?php

namespace Acme\GraphicBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ControlController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Acme\GraphicBundle\Controller\ControlController();
        return $instance;
    }
}
